version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gha:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gomod:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    groups:
      tools:
        patterns: ["*"]

  - package-ecosystem: "terraform"
    directory: "/integration"
    schedule:
      interval: "monthly"
    groups:
      integration:
        patterns: ["*"]
