version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      combined:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      combined:
        patterns: ["*"]

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    groups:
      tools:
        patterns: ["*"]
