version: '2'

services:
  runner:
    build:
      image: codeship
      dockerfile: codeship.dockerfile
    depends_on: [ jenkins-provider-acc ]
    cached: true

  jenkins-provider-acc:
    build:
      image: jenkins-provider-acc
      dockerfile: jenkins/test-fixtures/Dockerfile
    cached: true
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
