[tools]
"github:hashicorp/terraform-plugin-docs" = "latest"
go = "1.26"
terraform = "1.16"

[tasks.generate]
run = """
# Format Terraform code for use in documentation.
terraform fmt -recursive examples/
# Generate documentation.
tfplugindocs generate
"""
