version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker: &remote
          version: 18.06.0-ce
      - run: go get
      - run: make testacc
