version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get
      - run: mkdir -p ~/junit
      - run: gotestsum --junitfile "~/junit/junit.xml"
      - store_test_results:
          path: ~/junit
