version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get
      - run: mkdir -p /tmp/test-results
      - run: gotestsum --junitfile "/tmp/test-results/junit.xml"
      - store_test_results:
          path: /tmp/test-results
