version: '3.7'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: jenkins-provider-acc
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
